export default interface User {
    name: string,
    email: string,
    password: string,
    dob: Date,
    binusian: string,
    campus: string,
    gender: string,
    profileImage: string,
    premium: boolean,
    match: string[],
    request: string[],
    likedBy: string[],
    swipe: any,
    ref: FirebaseFirestore.DocumentReference,
    swipeCount: number,
    swipeDate: Date,
}